name: cinemax
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.1
  get: 4.6.1
  flutter: 
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  dotted_border: ^2.0.0+2
  splash_screen_view: ^3.0.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
  - family: MontserratSemiBold
    fonts:
      - asset: fonts/Montserrat-SemiBold.ttf
  - family: MontserratMedium
    fonts:
      - asset: fonts/Montserrat-Medium.ttf
  - family: MontserratRegular
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
